# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(502, 713)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButtonEmotion7 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion7.setObjectName("radioButtonEmotion7")
        self.horizontalLayout_4.addWidget(self.radioButtonEmotion7)
        self.radioButtonEmotion8 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion8.setObjectName("radioButtonEmotion8")
        self.horizontalLayout_4.addWidget(self.radioButtonEmotion8)
        self.radioButtonEmotion9 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion9.setObjectName("radioButtonEmotion9")
        self.horizontalLayout_4.addWidget(self.radioButtonEmotion9)
        self.radioButtonEmotion10 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion10.setObjectName("radioButtonEmotion10")
        self.horizontalLayout_4.addWidget(self.radioButtonEmotion10)
        self.radioButtonEmotion11 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion11.setObjectName("radioButtonEmotion11")
        self.horizontalLayout_4.addWidget(self.radioButtonEmotion11)
        self.gridLayout.addLayout(self.horizontalLayout_4, 17, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonEmotion1 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion1.setObjectName("radioButtonEmotion1")
        self.horizontalLayout_2.addWidget(self.radioButtonEmotion1)
        self.radioButtonEmotion2 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion2.setObjectName("radioButtonEmotion2")
        self.horizontalLayout_2.addWidget(self.radioButtonEmotion2)
        self.radioButtonEmotion3 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion3.setObjectName("radioButtonEmotion3")
        self.horizontalLayout_2.addWidget(self.radioButtonEmotion3)
        self.radioButtonEmotion4 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion4.setObjectName("radioButtonEmotion4")
        self.horizontalLayout_2.addWidget(self.radioButtonEmotion4)
        self.radioButtonEmotion5 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion5.setObjectName("radioButtonEmotion5")
        self.horizontalLayout_2.addWidget(self.radioButtonEmotion5)
        self.radioButtonEmotion6 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion6.setObjectName("radioButtonEmotion6")
        self.horizontalLayout_2.addWidget(self.radioButtonEmotion6)
        self.gridLayout.addLayout(self.horizontalLayout_2, 14, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButtonEmotion12 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion12.setObjectName("radioButtonEmotion12")
        self.horizontalLayout_5.addWidget(self.radioButtonEmotion12)
        self.radioButtonEmotion13 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion13.setObjectName("radioButtonEmotion13")
        self.horizontalLayout_5.addWidget(self.radioButtonEmotion13)
        self.radioButtonEmotion14 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion14.setObjectName("radioButtonEmotion14")
        self.horizontalLayout_5.addWidget(self.radioButtonEmotion14)
        self.radioButtonEmotion15 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion15.setObjectName("radioButtonEmotion15")
        self.horizontalLayout_5.addWidget(self.radioButtonEmotion15)
        self.gridLayout.addLayout(self.horizontalLayout_5, 18, 0, 1, 1)
        self.instrumentBox = QtWidgets.QComboBox(Dialog)
        self.instrumentBox.setObjectName("instrumentBox")
        self.instrumentBox.addItem("")
        self.instrumentBox.addItem("")
        self.instrumentBox.addItem("")
        self.instrumentBox.addItem("")
        self.instrumentBox.addItem("")
        self.gridLayout.addWidget(self.instrumentBox, 11, 0, 1, 1)
        self.deviceBox = QtWidgets.QComboBox(Dialog)
        self.deviceBox.setObjectName("deviceBox")
        self.gridLayout.addWidget(self.deviceBox, 4, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 9, 0, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.confirmButton = QtWidgets.QPushButton(Dialog)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)
        self.editButton = QtWidgets.QPushButton(Dialog)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.deviceChoices = QtWidgets.QLabel(Dialog)
        self.deviceChoices.setWordWrap(True)
        self.deviceChoices.setObjectName("deviceChoices")
        self.gridLayout.addWidget(self.deviceChoices, 3, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 12, 0, 1, 1)
        self.deviceChoices_4 = QtWidgets.QLabel(Dialog)
        self.deviceChoices_4.setWordWrap(True)
        self.deviceChoices_4.setObjectName("deviceChoices_4")
        self.gridLayout.addWidget(self.deviceChoices_4, 13, 0, 1, 1)
        self.dirPath = QtWidgets.QLabel(Dialog)
        self.dirPath.setWordWrap(True)
        self.dirPath.setObjectName("dirPath")
        self.gridLayout.addWidget(self.dirPath, 0, 0, 1, 1)
        self.deviceChoices_3 = QtWidgets.QLabel(Dialog)
        self.deviceChoices_3.setWordWrap(True)
        self.deviceChoices_3.setObjectName("deviceChoices_3")
        self.gridLayout.addWidget(self.deviceChoices_3, 10, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 1)
        self.timeLabel = QtWidgets.QLabel(Dialog)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout.addWidget(self.timeLabel, 24, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 23, 0, 1, 1)
        self.browseButton = QtWidgets.QPushButton(Dialog)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 1, 0, 1, 1)
        self.promptLabel = QtWidgets.QLabel(Dialog)
        self.promptLabel.setText("")
        self.promptLabel.setWordWrap(True)
        self.promptLabel.setObjectName("promptLabel")
        self.gridLayout.addWidget(self.promptLabel, 27, 0, 1, 1)
        self.recordButton = QtWidgets.QPushButton(Dialog)
        self.recordButton.setObjectName("recordButton")
        self.gridLayout.addWidget(self.recordButton, 25, 0, 1, 1)
        self.stopButton = QtWidgets.QPushButton(Dialog)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 26, 0, 1, 1)
        self.deviceChoices_2 = QtWidgets.QLabel(Dialog)
        self.deviceChoices_2.setWordWrap(True)
        self.deviceChoices_2.setObjectName("deviceChoices_2")
        self.gridLayout.addWidget(self.deviceChoices_2, 6, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Emotional Music Recorder"))
        self.radioButtonEmotion7.setText(_translate("Dialog", "Cluster 1"))
        self.radioButtonEmotion8.setText(_translate("Dialog", "Cluster 2"))
        self.radioButtonEmotion9.setText(_translate("Dialog", "Cluster 3"))
        self.radioButtonEmotion10.setText(_translate("Dialog", "Cluster 4"))
        self.radioButtonEmotion11.setText(_translate("Dialog", "Cluster 5"))
        self.radioButtonEmotion1.setText(_translate("Dialog", "Anger"))
        self.radioButtonEmotion2.setText(_translate("Dialog", "Disgust"))
        self.radioButtonEmotion3.setText(_translate("Dialog", "Fear"))
        self.radioButtonEmotion4.setText(_translate("Dialog", "Happiness"))
        self.radioButtonEmotion5.setText(_translate("Dialog", "Sadness"))
        self.radioButtonEmotion6.setText(_translate("Dialog", "Surprise"))
        self.radioButtonEmotion12.setText(_translate("Dialog", "Quadrant 1"))
        self.radioButtonEmotion13.setText(_translate("Dialog", "Quadrant 2"))
        self.radioButtonEmotion14.setText(_translate("Dialog", "Quadrant 3"))
        self.radioButtonEmotion15.setText(_translate("Dialog", "Quadrant 4"))
        self.instrumentBox.setItemText(0, _translate("Dialog", "Piano"))
        self.instrumentBox.setItemText(1, _translate("Dialog", "Violin"))
        self.instrumentBox.setItemText(2, _translate("Dialog", "Cello"))
        self.instrumentBox.setItemText(3, _translate("Dialog", "Trumpet"))
        self.instrumentBox.setItemText(4, _translate("Dialog", "Saxophone"))
        self.confirmButton.setText(_translate("Dialog", "Confirm"))
        self.editButton.setText(_translate("Dialog", "Edit"))
        self.deviceChoices.setText(_translate("Dialog", "Audio Device"))
        self.deviceChoices_4.setText(_translate("Dialog", "Emotion"))
        self.dirPath.setText(_translate("Dialog", "Directory of Dataset"))
        self.deviceChoices_3.setText(_translate("Dialog", "Instrument"))
        self.timeLabel.setText(_translate("Dialog", "00:00"))
        self.browseButton.setText(_translate("Dialog", "Browse..."))
        self.recordButton.setText(_translate("Dialog", "Record"))
        self.stopButton.setText(_translate("Dialog", "Stop"))
        self.deviceChoices_2.setText(_translate("Dialog", "Musician\'s Name"))

