# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(379, 722)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dirPath = QtWidgets.QLabel(Dialog)
        self.dirPath.setWordWrap(True)
        self.dirPath.setObjectName("dirPath")
        self.verticalLayout.addWidget(self.dirPath)
        self.browseButton = QtWidgets.QPushButton(Dialog)
        self.browseButton.setObjectName("browseButton")
        self.verticalLayout.addWidget(self.browseButton)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.deviceChoices = QtWidgets.QLabel(Dialog)
        self.deviceChoices.setWordWrap(True)
        self.deviceChoices.setObjectName("deviceChoices")
        self.verticalLayout.addWidget(self.deviceChoices)
        self.deviceBox = QtWidgets.QComboBox(Dialog)
        self.deviceBox.setObjectName("deviceBox")
        self.verticalLayout.addWidget(self.deviceBox)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.deviceChoices_2 = QtWidgets.QLabel(Dialog)
        self.deviceChoices_2.setWordWrap(True)
        self.deviceChoices_2.setObjectName("deviceChoices_2")
        self.verticalLayout.addWidget(self.deviceChoices_2)
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout.addWidget(self.nameEdit)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.deviceChoices_3 = QtWidgets.QLabel(Dialog)
        self.deviceChoices_3.setWordWrap(True)
        self.deviceChoices_3.setObjectName("deviceChoices_3")
        self.verticalLayout.addWidget(self.deviceChoices_3)
        self.instrumentBox = QtWidgets.QComboBox(Dialog)
        self.instrumentBox.setObjectName("instrumentBox")
        self.instrumentBox.addItem("")
        self.instrumentBox.addItem("")
        self.instrumentBox.addItem("")
        self.instrumentBox.addItem("")
        self.instrumentBox.addItem("")
        self.verticalLayout.addWidget(self.instrumentBox)
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.deviceChoices_4 = QtWidgets.QLabel(Dialog)
        self.deviceChoices_4.setWordWrap(True)
        self.deviceChoices_4.setObjectName("deviceChoices_4")
        self.verticalLayout.addWidget(self.deviceChoices_4)
        self.radioButtonEmotion1 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion1.setObjectName("radioButtonEmotion1")
        self.verticalLayout.addWidget(self.radioButtonEmotion1)
        self.radioButtonEmotion2 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion2.setObjectName("radioButtonEmotion2")
        self.verticalLayout.addWidget(self.radioButtonEmotion2)
        self.radioButtonEmotion3 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion3.setObjectName("radioButtonEmotion3")
        self.verticalLayout.addWidget(self.radioButtonEmotion3)
        self.radioButtonEmotion4 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion4.setObjectName("radioButtonEmotion4")
        self.verticalLayout.addWidget(self.radioButtonEmotion4)
        self.radioButtonEmotion5 = QtWidgets.QRadioButton(Dialog)
        self.radioButtonEmotion5.setObjectName("radioButtonEmotion5")
        self.verticalLayout.addWidget(self.radioButtonEmotion5)
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.timeLabel = QtWidgets.QLabel(Dialog)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout.addWidget(self.timeLabel)
        self.recordButton = QtWidgets.QPushButton(Dialog)
        self.recordButton.setObjectName("recordButton")
        self.verticalLayout.addWidget(self.recordButton)
        self.stopButton = QtWidgets.QPushButton(Dialog)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout.addWidget(self.stopButton)
        self.promptLabel = QtWidgets.QLabel(Dialog)
        self.promptLabel.setText("")
        self.promptLabel.setWordWrap(True)
        self.promptLabel.setObjectName("promptLabel")
        self.verticalLayout.addWidget(self.promptLabel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Emotional Music Recorder"))
        self.dirPath.setText(_translate("Dialog", "Directory of Dataset"))
        self.browseButton.setText(_translate("Dialog", "Browse..."))
        self.deviceChoices.setText(_translate("Dialog", "Audio Device"))
        self.deviceChoices_2.setText(_translate("Dialog", "Musician\'s Name"))
        self.deviceChoices_3.setText(_translate("Dialog", "Instrument"))
        self.instrumentBox.setItemText(0, _translate("Dialog", "Piano"))
        self.instrumentBox.setItemText(1, _translate("Dialog", "Violin"))
        self.instrumentBox.setItemText(2, _translate("Dialog", "Cello"))
        self.instrumentBox.setItemText(3, _translate("Dialog", "Trumpet"))
        self.instrumentBox.setItemText(4, _translate("Dialog", "Saxophone"))
        self.deviceChoices_4.setText(_translate("Dialog", "Emotion"))
        self.radioButtonEmotion1.setText(_translate("Dialog", "Passionate"))
        self.radioButtonEmotion2.setText(_translate("Dialog", "Cheerful"))
        self.radioButtonEmotion3.setText(_translate("Dialog", "Bittersweet"))
        self.radioButtonEmotion4.setText(_translate("Dialog", "Quirky"))
        self.radioButtonEmotion5.setText(_translate("Dialog", "Aggressive"))
        self.timeLabel.setText(_translate("Dialog", "00:00"))
        self.recordButton.setText(_translate("Dialog", "Record"))
        self.stopButton.setText(_translate("Dialog", "Stop"))

